import type { Metadata } from "next"
import { GeistSans } from "geist/font/sans"

import { cn } from "@/lib/utils"
import DevThemeToggler from "@/components/dev-theme-toggler"
import { ThemeProvider } from "@/components/theme-provider"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn(GeistSans.variable)} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <DevThemeToggler />
        </ThemeProvider>
      </body>
    </html>
  )
}
